version: 2.1

jobs:
  test:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run:
          name: Unit tests
          command: ./scripts/unit.sh

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
